apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tiddlywiki
  name: tiddlywiki
  namespace: apps
spec:
  selector:
    matchLabels:
      app: tiddlywiki
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tiddlywiki
    spec:
      containers:
      - image: vemcompy/tiddlywiki:latest
        imagePullPolicy: Always
        name: tiddlywiki
        env:
        - name: wiki_name
          value: vemcompy
        - name: wiki_port
          value: "8080"
        - name: wiki_username
          value: admin
        - name: wiki_password
          value: admin
        - name: gzip
          value: "yes"
        - name: "debug-level"
          value: "none"
        volumeMounts:
        - mountPath: /app/vemcompy
          name: volume
      volumes:
      - name: volume
        hostPath:
          path: /data 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
